### ISSUE TITLE
Unable to flash Shine Wifi-X

### ISSUE THREAD

**Issue by hemmingsentfromhell** [pvprodk/GrowattESPHome#2]
Hi there

I am unable to flash the Shine WiFi X following your procedure. (Connecting the marked pins on the board while booting). 

My ESPHome Web flasher connects to a "USB Serial Device (COM15)", but when I start to flash it just keeps spinning and writes "Connecting" 

I also tried via the Home Assistant NUC, but again it fails with this message:

```
esptool.py v4.6.2
Serial port /dev/ttyACM0
Connecting......
ERROR Running command failed: Write timeout
ERROR Please try running esptool.py --before default_reset --after hard_reset --baud 460800 --port /dev/ttyACM0 --chip esp8266 write_flash -z --flash_size detect 0x0 /data/build/growatt/.pioenvs/growatt/firmware.bin locally.
INFO Upload with baud rate 460800 failed. Trying again with baud rate 115200.
esptool.py v4.6.2
Serial port /dev/ttyACM0
Connecting...
ERROR Running command failed: Write timeout
ERROR Please try running esptool.py --before default_reset --after hard_reset --baud 115200 --port /dev/ttyACM0 --chip esp8266 write_flash -z --flash_size detect 0x0 /data/build/growatt/.pioenvs/growatt/firmware.bin locally.

``` 

Do you have any more tips? How long should it take?

**Comment by vaibhavratnaparkhi** [comment]
Do you have a detailed picture of the setup?

**Comment by pvprodk** [comment]
> Do you have any more tips? How long should it take?

Sometime you need to update the USB-to-SERIAL port driver, and/or disable FIFO buffers on the serial port in device manager.

**Comment by pvprodk** [comment]
Please see additional info regarding flashing at this site: https://esphome.io/guides/physical_device_connection.html
