### ISSUE TITLE
Additonal pictures

### ISSUE THREAD

**Issue by vaibhavratnaparkhi** [pvprodk/GrowattESPHome#4]
The description mentions the below:'
'To flash the ShineWifi-X with ESPHome you need to put it into boot mode, by jumping the GPIO0 and GND pins while plugging in/powering on the USB-device. Important to remove the jumper before you flash:

Can it be possible to attach a few more pictures of how to jump the 2 pins and any other pictures.

In order to power the shine stick, can it be just connected to the usb on the laptop? or ?

while flashing - should it be connected to the laptop usb?

Maybe newbie questions, but hopefully someone can help.

**Comment by pvprodk** [comment]
No additional pictures needed to be honest. You simply jump the two pins while plugging the stick in to your USB Port, and removes the jumper after a few seconds. Then you proceed to flash the stick via USB. The stick will be powered by PC USB port while flashing.

More info regarding physical connections etc: https://esphome.io/guides/physical_device_connection.html

**Comment by vaibhavratnaparkhi** [comment]
Thank you so much!!
