### ISSUE TITLE
Different version of dongle

### ISSUE THREAD

**Issue by Rayeliint** [pvprodk/GrowattESPHome#5]
Hi there, looks like I have a different version dongle. It does not have the same GPIO0 in your image?
Any ideas how I enter boot mode?
![2024-01-23 17 43 11](https://github.com/pvprodk/GrowattESPHome/assets/72634673/e1ea332e-42c1-426f-abf5-8b6df6b651af)

**Comment by pvprodk** [comment]
This is not a ShineWifi-X hence it does not run 2.4GHz wifi, but it runs a different RF protocol on 433Mhz. The RF-stick is designed to be used with a ShineLink-X (ShineLanBox). I dont even think this one is ESP Based, however I might be wrong on that. I dont think you can make this work with ESPHome
